/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.LivrosDAO;
import MODEL.LivrosMODEL;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author PuddinAPX
 */
public class LivrosVIEW extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form LivrosVIEW
     */
    public LivrosVIEW() {
        initComponents();
        Botoes();
        listarlivros();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLIVROS = new javax.swing.JButton();
        btnCADASTRAR = new javax.swing.JButton();
        btnEMPRESTIMO = new javax.swing.JButton();
        btnDEVOLUCAO = new javax.swing.JButton();
        btnHOME = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnEDITAR = new javax.swing.JButton();
        btnATUALIZAR = new javax.swing.JButton();
        btnEXCLUIR = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIBLIOTECH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        btnLIVROS.setBackground(new java.awt.Color(0, 0, 0));
        btnLIVROS.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLIVROS.setForeground(new java.awt.Color(255, 255, 255));
        btnLIVROS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/livro.png"))); // NOI18N
        btnLIVROS.setText("  Livros");
        btnLIVROS.setBorder(null);
        btnLIVROS.setPreferredSize(new java.awt.Dimension(57, 50));
        btnLIVROS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIVROSActionPerformed(evt);
            }
        });
        jPanel1.add(btnLIVROS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, -1));

        btnCADASTRAR.setBackground(new java.awt.Color(0, 0, 0));
        btnCADASTRAR.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCADASTRAR.setForeground(new java.awt.Color(255, 255, 255));
        btnCADASTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/conecte-se (1) (1).png"))); // NOI18N
        btnCADASTRAR.setText("Cadastrar");
        btnCADASTRAR.setBorder(null);
        btnCADASTRAR.setPreferredSize(new java.awt.Dimension(57, 50));
        btnCADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCADASTRARActionPerformed(evt);
            }
        });
        jPanel1.add(btnCADASTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, -1));

        btnEMPRESTIMO.setBackground(new java.awt.Color(0, 0, 0));
        btnEMPRESTIMO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEMPRESTIMO.setForeground(new java.awt.Color(255, 255, 255));
        btnEMPRESTIMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/emprestimo.png"))); // NOI18N
        btnEMPRESTIMO.setText("Emprestar");
        btnEMPRESTIMO.setBorder(null);
        btnEMPRESTIMO.setPreferredSize(new java.awt.Dimension(57, 50));
        btnEMPRESTIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMPRESTIMOActionPerformed(evt);
            }
        });
        jPanel1.add(btnEMPRESTIMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, -1));

        btnDEVOLUCAO.setBackground(new java.awt.Color(0, 0, 0));
        btnDEVOLUCAO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDEVOLUCAO.setForeground(new java.awt.Color(255, 255, 255));
        btnDEVOLUCAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/devolucao.png"))); // NOI18N
        btnDEVOLUCAO.setText(" Devolver");
        btnDEVOLUCAO.setBorder(null);
        btnDEVOLUCAO.setPreferredSize(new java.awt.Dimension(57, 50));
        btnDEVOLUCAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEVOLUCAOActionPerformed(evt);
            }
        });
        jPanel1.add(btnDEVOLUCAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, 210, -1));

        btnHOME.setBackground(new java.awt.Color(0, 0, 0));
        btnHOME.setForeground(new java.awt.Color(0, 0, 0));
        btnHOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pinguin.png (2).png"))); // NOI18N
        btnHOME.setBorder(null);
        btnHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHOMEActionPerformed(evt);
            }
        });
        jPanel1.add(btnHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 89, 86));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaLivros.setBackground(new java.awt.Color(255, 255, 255));
        tabelaLivros.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tabelaLivros.setForeground(new java.awt.Color(0, 0, 0));
        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "LIVRO", "EDITORA", "AUTOR", "CATEGORIA", "STATUS ", "R$", "ANO ", "COD."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaLivros.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaLivros.setRowHeight(40);
        tabelaLivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaLivros);
        if (tabelaLivros.getColumnModel().getColumnCount() > 0) {
            tabelaLivros.getColumnModel().getColumn(0).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(0).setPreferredWidth(3);
            tabelaLivros.getColumnModel().getColumn(1).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaLivros.getColumnModel().getColumn(2).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabelaLivros.getColumnModel().getColumn(3).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabelaLivros.getColumnModel().getColumn(4).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(4).setPreferredWidth(80);
            tabelaLivros.getColumnModel().getColumn(5).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(6).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(6).setPreferredWidth(20);
            tabelaLivros.getColumnModel().getColumn(7).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(7).setPreferredWidth(20);
            tabelaLivros.getColumnModel().getColumn(8).setResizable(false);
            tabelaLivros.getColumnModel().getColumn(8).setPreferredWidth(60);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 930, 490));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 10));

        btnEDITAR.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/botao-editar (1).png"))); // NOI18N
        btnEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITARActionPerformed(evt);
            }
        });
        jPanel2.add(btnEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        btnATUALIZAR.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnATUALIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refrescar (1).png"))); // NOI18N
        btnATUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATUALIZARActionPerformed(evt);
            }
        });
        jPanel2.add(btnATUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, -1));

        btnEXCLUIR.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEXCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excluir (1).png"))); // NOI18N
        btnEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXCLUIRActionPerformed(evt);
            }
        });
        jPanel2.add(btnEXCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 90, -1));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(null);
        txtID.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtID.setEnabled(false);
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 940, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLIVROSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIVROSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLIVROSActionPerformed

    private void btnCADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCADASTRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCADASTRARActionPerformed

    private void btnEMPRESTIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMPRESTIMOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEMPRESTIMOActionPerformed

    private void btnDEVOLUCAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEVOLUCAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDEVOLUCAOActionPerformed

    private void btnHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHOMEActionPerformed

    private void btnEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITARActionPerformed
        Editar();
        
    }//GEN-LAST:event_btnEDITARActionPerformed

    private void btnATUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATUALIZARActionPerformed
        listarlivros();
    }//GEN-LAST:event_btnATUALIZARActionPerformed

    private void btnEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXCLUIRActionPerformed
        Excluir();
        listarlivros();
    }//GEN-LAST:event_btnEXCLUIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivrosVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnATUALIZAR;
    private javax.swing.JButton btnCADASTRAR;
    private javax.swing.JButton btnDEVOLUCAO;
    private javax.swing.JButton btnEDITAR;
    private javax.swing.JButton btnEMPRESTIMO;
    private javax.swing.JButton btnEXCLUIR;
    private javax.swing.JButton btnHOME;
    private javax.swing.JButton btnLIVROS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    protected javax.swing.JTable tabelaLivros;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

    public void Botoes() {
        JButton[] btns = {btnHOME, btnLIVROS, btnCADASTRAR, btnEMPRESTIMO, btnDEVOLUCAO};
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        for (JButton btn : btns) {
            btn.setBackground(new Color(0, 0, 0));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                }

                @Override
                public void mousePressed(MouseEvent me) {
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    btn.setBackground(new Color(28, 28, 28));
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    btn.setBackground(new Color(0, 0, 0));
                }

                @Override
                public void mouseReleased(MouseEvent me) {
                }
            });
        }
        btnDEVOLUCAO.addActionListener((e) -> {
            this.setVisible(false);
            new DevolucaoVIEW();
        });
        btnEMPRESTIMO.addActionListener((e) -> {
            this.setVisible(false);
            new EmprestimoVIEW();
        });
        btnCADASTRAR.addActionListener((e) -> {
            this.setVisible(false);
            new CadastroVIEW();
        });
        btnHOME.addActionListener((e) -> {
            this.setVisible(false);
            new HomeVIEW();
        });
        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        this.setVisible(false);
        new HomeVIEW();
    }

    public void listarlivros() {
        try {
            LivrosDAO objlivrosD = new LivrosDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaLivros.getModel();
            model.setNumRows(0);

            ArrayList<LivrosMODEL> lista = objlivrosD.listarLivros();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getNomeLivro(),
                    lista.get(num).getEditora(),
                    lista.get(num).getAutor(),
                    lista.get(num).getCategoria(),
                    lista.get(num).getStatusLivro(),
                    lista.get(num).getValorLivro(),
                    lista.get(num).getAnoLancamento(),
                    lista.get(num).getCodLivro()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarLivros VIEW: " + erro);
        }
    }

    public void Editar() {
        int setar = tabelaLivros.getSelectedRow();

        if (tabelaLivros.getSelectedRow() != -1) {
            EditarVIEW objLivroVE = new EditarVIEW();
            objLivroVE.setVisible(true);

            objLivroVE.txtID.setText(tabelaLivros.getModel().getValueAt(setar, 0).toString());
            objLivroVE.txtNome.setText(tabelaLivros.getModel().getValueAt(setar, 1).toString());
            objLivroVE.txtEditora.setText(tabelaLivros.getModel().getValueAt(setar, 2).toString());
            objLivroVE.txtAutor.setText(tabelaLivros.getModel().getValueAt(setar, 3).toString());
            objLivroVE.txtCategoria.setText(tabelaLivros.getModel().getValueAt(setar, 4).toString());
            objLivroVE.txtValor.setText(tabelaLivros.getModel().getValueAt(setar, 6).toString());
            objLivroVE.txtAno.setText(tabelaLivros.getModel().getValueAt(setar, 7).toString());
            objLivroVE.txtCodlivro.setText(tabelaLivros.getModel().getValueAt(setar, 8).toString());
        }

    }

    public void Excluir() {
        int id_livro;

        int setar = tabelaLivros.getSelectedRow();

        if (tabelaLivros.getSelectedRow() != -1) {
          int resultado = JOptionPane.showConfirmDialog(null, "Deseja excluir este livro?");
            if (resultado == JOptionPane.YES_OPTION) {
                txtID.setText(tabelaLivros.getModel().getValueAt(setar, 0).toString());

                id_livro = Integer.parseInt(txtID.getText());

                LivrosMODEL objlivrosM = new LivrosMODEL();
                objlivrosM.setId(id_livro);

                LivrosDAO objlivrosD = new LivrosDAO();
                objlivrosD.ExcluirLivro(objlivrosM);
                
                JOptionPane.showMessageDialog(null, "Livro deletado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } 
        } else{
            JOptionPane.showMessageDialog(null, "Selecione o livro que deseja excluir", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }
}
